[package]
name = "scribe"
version = "0.1.0"
authors = ["Francisco Gómez García <espectalll@kydara.com>"]

[dependencies]
gio = "^0.1.2"
gtk = { version = "^0.1.2", features = ["v3_20"] }
webkit2gtk = { git = "https://github.com/antoyo/webkit2gtk-rs.git" }
html5ever = "0.17"
